version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    env_file:
      - ./backend/.env.example
    environment:
      - MONGO_URI=mongodb://mongo:27017/hs-chat
      - PORT=4000
      - FRONTEND_ORIGIN=http://localhost:5173
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    environment:
      - VITE_API_URL=http://localhost:4000/api
      - VITE_SOCKET_URL=http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
